pr:
  - master

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: build
    jobs:
      - job: build_mvc
        steps:
          - script: dotnet build Contagion/Contagion.MVC/*.csproj
      - job: build_api
        steps:
          - script: dotnet build Contagion/Contagion.API/*.csproj

  # - stage: test
  #   jobs:
  #     - job: test_mvc
  #     - job: test_api


  # - stage: analyze
  #   jobs:
  #     - job: analyze_mvc
  #       pool:
  #         vmImage: ubuntu-18.04
  #       steps:
  #         - task: DotnetGlobalToolInstaller@0
  #           inputs:
  #             name: "dotnet-sonarscanner"
  #         - script: |
  #             dotnet sonarscanner begin /k:"p2-Contagion" /o:"team-contagion" /d:sonar.host.url="https://sonarcloud.io/"
  #             dotnet build Contagion/*.sln
  #             dotnet sonarscanner end


      # - job: analyze_api
      #   pool:
      #     vmImage: ubuntu-18.04
      #   steps:
      #     - task: DotnetGlobalToolInstaller@0
      #       inputs:
      #         name: "dotnet-sonarscanner"
      #     - script: |
      #         dotnet sonarscanner begin /k:"p2-Contagion" /o:"team-contagion" /d:sonar.host.url="https://sonarcloud.io/"
      #         dotnet build Contagion/*.sln
      #         dotnet sonarscanner end

  - stage: pack
    jobs:
      - job: pack_mvc
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file .docker/mvc.dockerfile --tag bennetcd/mvcproj Contagion/Contagion.MVC
              docker image push bennetcd/mvcproj
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker
      - job: pack_api
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file .docker/api.dockerfile --tag bennetcd/apiproj Contagion/Contagion.API
              docker image push bennetcd/apiproj
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker


  - stage: deploy
    jobs:
      - job: deploy_app
        steps:
          - task: DockerCompose@0
            displayName: Run services
            inputs:
              action: Run services
              dockerRegistry: Contagion
              containerRegistryType: Container Registry
              dockerComposeFile: docker-compose.yaml
              projectName: p2
              buildImages: false
              detached: true


trigger:
  - master