version: "3.7"

services:

  api:
    build:
      context: Contagion/Contagion.API
      dockerfile: ../../.docker/api.dockerfile
    image: bennetcd/apiproj
    ports:
      - 0:80
    networks:
      - newt

  mvc:
    build:
      context: Contagion/Contagion.MVC
      dockerfile: ../../.docker/mvc.dockerfile
    image: bennetcd/mvcproj
    ports:
      - 4000:80
    networks:
      - newt
    environment:
      ConnectionStrings__main: "server=sql;database=contagiondb;user id=sa;password=Password12345"
      
  # sql:
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Password12345
  #   networks:
  #     - newt
  #   ports:
  #     - 1433:1433
      

networks:
  newt:


# services:
#   app:
#     image: fredbelotte/p1proj
#     networks:
#       - skynet
#     ports:
#       - 8000:80
#     environment:
#       ConnectionStrings__main: "server=sql;database=PizzaBoxDb;user id=sa;password=Password12345"

#   sql:
#     image: mcr.microsoft.com/mssql/server:2017-latest
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Password12345
#     networks:
#       - newt
#     ports:
#       - 1433:1433

#docker-compose -f docker-compose.yaml up --build
